version: '3.8'

services:
  api:
    ports:
      - "80:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Staging
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=superqa;User=${MYSQL_USER};Password=${MYSQL_PASSWORD};Port=3306;
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
      replicas: 2

  frontend:
    build:
      args:
        - BUILD_ENV=staging
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      replicas: 2

  mysql:
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=superqadb
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G 